# Generated by Django 6.0.8 on 2026-08-11 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Patient's Full Name")),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (kg)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Height (cm)')),
                ('medical_diagnosis', models.TextField(verbose_name='Diagnosis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients_created', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.TextField(verbose_name='Treatment / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments_created', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patient')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
