# Generated by Django 6.0.8 on 2026-08-19 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='number',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 10 digits.', regex='^\\d{10}$')], verbose_name='Phone No'),
        ),
    ]
